desiredState:
  manifest:
    containers:
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: HEAT_DB_PASSWORD
        value: password
      - name: HEAT_KEYSTONE_PASSWORD
        value: password
      image: kollaglue/fedora-rdo-heat-engine
      name: heat-engine
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: HEAT_DB_PASSWORD
        value: password
      - name: HEAT_KEYSTONE_PASSWORD
        value: password
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-heat-api
      name: heat-api
      ports:
      - containerPort: 8004
    id: heat-1
    version: v1beta1
id: heat
apiVersion: v1beta1
kind: Pod
labels:
  name: heat
