#!/bin/sh

cd $(git rev-parse --show-toplevel)

pods='
rabbitmq
mariadb
keystone
glance
nova-controller
nova-compute
neutron-controller
heat
mongodb
ceilometer-controller
zaqar
horizon
'

for pod in $pods; do
    kubectl create -f "k8s/pod/${pod}-pod.yaml"
done

